development:
  adapter: postgresql
  encoding: unicode
  database: pinterest_clone_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  encoding: unicode
  database: pinterest_clone_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: pinterest_clone_production
  pool: 5
  timeout: 5000
